version: "3.7"

networks:
    seedtoken_lan:
        name: ${NETWORK_NAME}
        driver: bridge

services:
    mailhog:
        image: mailhog/mailhog
        networks:
            - ${NETWORK_NAME}
        ports:
            - ${MAILHOG_SMTP_PORT}:1025
            - ${MAILHOG_HTTP_PORT}:8025

    redis:
        image: redis:5-alpine
        command: redis-server --requirepass "${REDIS_PASSWORD}"
        networks:
            - ${NETWORK_NAME}
        ports:
            -  ${REDIS_PORT}:6379

    postgresql:
        build: ./postgresql/
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_PORT=${POSTGRES_PORT}
            - ACCOUNTS_DATABASE=${ACCOUNTS_DATABASE}
            - ACCOUNTS_TEST_DATABASE=${ACCOUNTS_TEST_DATABASE}
            - WALLET_DATABASE=${WALLET_DATABASE}
            - WALLET_TEST_DATABASE=${WALLET_TEST_DATABASE}
            - GREENHOUSE_DATABASE=${GREENHOUSE_DATABASE}
            - GREENHOUSE_TEST_DATABASE=${GREENHOUSE_TEST_DATABASE}
        networks:
            - ${NETWORK_NAME}
        volumes:
            - ./volumes/postgresql/var/lib/postgresql/data:/var/lib/postgresql/data
        ports:
            - ${POSTGRES_PORT}:5432
        expose:
            - ${POSTGRES_PORT}

    parity:
        image: parity/parity:v2.5.5-stable
        command:
            --config dev-insecure
            --tracing=on
            --jsonrpc-interface=all
            --jsonrpc-hosts=all
            --jsonrpc-apis=all
            --ws-origins=all
            --ws-hosts=all
            --ws-interface=all
            --fat-db=on
            --pruning=archive
            --jsonrpc-cors=all
            --network-id=1010
        networks:
            - ${NETWORK_NAME}
        ports:
            - ${PARITY_JSON_RPC_PORT}:8545
            - ${PARITY_WEB_SOCKETS_PORT}:8546
            - ${PARITY_ETHEREUM_PORT}:30303
            - ${PARITY_ETHEREUM_PORT}:30303/udp
        user: root
        volumes:
            - ./volumes/io.parity.ethereum:/root/.local/share/io.parity.ethereum

    mongo:
        image: mongo:4.0.11
        networks:
            - ${NETWORK_NAME}
        ports:
            - 0.0.0.0:${MONGO_PORT}:27017
        command: mongod --smallfiles --logpath=/dev/null
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
            - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
            - AUTH=yes
        volumes:
            - ./volumes/data/db:/data/db
            - ./volumes/var/log/mongodb:/var/log/mongodb
            - ./volumes/home/mongodb:/home/mongodb

    mongo-express:
        image: mongo-express
        networks:
            - ${NETWORK_NAME}
        ports:
            - ${MONGO_EXPRESS_PORT}:8081
        environment:
            - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_USER}
            - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_PASSWORD}
        depends_on:
            - mongo

    explorer:
        build:
            context: https://github.com/SeedVault/blockexplorer.git#initial:blockexplorer
            dockerfile: docker/Dockerfile
            args:
                SECRET_KEY_BASE: ${BLOCKSCOUT_SECRET_KEY_BASE}
                COIN_NAME: ${BLOCKSCOUT_COIN_NAME}
        restart: always
        volumes:
        - ./volumes/blockexplorer:/apps
        environment:
            - SUBNETWORK=SEED-Testnet
            - LOGO=/images/seed-logo.svg
            - LOGO_FOOTER=/images/seed-footer-logo.svg
            - ETHEREUM_JSONRPC_VARIANT=parity
            - COIN=
            - SECRET_KEY_BASE=${BLOCKSCOUT_SECRET_KEY_BASE}
            - ETHEREUM_JSONRPC_HTTP_URL=http://parity:${PARITY_JSON_RPC_PORT}
            - ETHEREUM_JSONRPC_TRACE_URL=http://parity:${PARITY_JSON_RPC_PORT}
            - ETHEREUM_JSONRPC_WS_URL=ws://parity:${PARITY_WEB_SOCKETS_PORT}
            - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgresql:5432/explorer?ssl=false
        networks:
            - ${NETWORK_NAME}
        ports:
            - ${BLOCKSCOUT_PORT}:4000
        depends_on:
            - postgresql
            - parity
        command:
            - ./run.sh
        
